<?php


/**
 * Implement hook_menu().
 *
 * @return
 *   An array of menu items.
 */
function bunchball_menu() {
  $items = array();

  $items['admin/config/bunchball'] = array(
    'title' => 'Bunchball configuration',
    'description' => 'The main configuration screen for the bunchball api modules',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bunchball_admin_form'),
    'access arguments' => array('configure bunchball'),
    'file' => 'bunchball.admin.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -10,
  );

  $items['admin/config/bunchball/main'] = array(
    'title' => 'Bunchball configuration',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function bunchball_permission() {
  return array(
    'configure bunchball' => array(
      'title' => t('Configure Bunchball settings'),
      'description' => t('Users allowed to configure the core bunchball module including reading or writing Bunchball API keys.'),
    ),
  );
}


/**
 * Implement hook_help()
 */
function bunchball_help($path, $arg) {
   if ($path == 'admin/help#bunchball') {
    return t("Here is a stub help page.  We'll need one eventually.");
  }
}