<?php

/**
 * Implements hook_cron_queue_info().
 */
function bunchball_queue_cron_queue_info() {
  return array(
    'bunchball_request_queue' => array(
      'worker callback' => 'bunchball_queue_request_queue_worker',
      // default timeout of 15 sec should be ok.
    ),
  );
}

/**
 * Queue worker callback.
 *
 * @param $job
 *   An associative array containing the keys:
 *     - url: The url of the request
 *     - options: any options to pass onto the request.  These can be assumed to
 *       be the same as options for drupal_http_request for the time being, but
 *       may change along with the backend HTTP client.
 */
function bunchball_queue_request_queue_worker($job) {
  $valid_options = array_fill_keys(array('headers', 'method', 'data', 'max_redirects', 'timeout', 'context'), 0);
  $options = array_intersect_key($job['options'], $valid_options);

  $options += array(
    // default timeout of 5 seconds - relatively short so processes don't hang,
    // but should be long enough for most normal use.
    'timeout' => 5.0,
  );
  bunchball_debug('Retrieved queued job for url: %url', array('%url' => $job['url']));
  $response = drupal_http_request($job['url'], $options);
  bunchball_debug('Queued job response code: %code', array('%code' => $response->code));
  if ($response->code != 200) {
    bunchball_debug('Queued job error: %response', array('%response' => print_r($response, TRUE)));
    watchdog('bunchball', 'Bunchball API call returned non-200 status: %response', array('%response' => print_r($response, true)), WATCHDOG_ERROR);
  }
  else {
    $xml = new simpleXMLElement($response->data);
    $result = strval(reset($xml->xpath('/Nitro/@res')));
    bunchball_debug('Queued job result: %result', array('%result' => $result));
    if ($result != 'ok') {
      watchdog('bunchball', 'Nitro API log action failed', array(), WATCHDOG_WARNING);
    }
  }
}

/**
 * Implements hook_FORMID_alter().
 *
 * @see bunchball_admin_form()
 */
function bunchball_queue_form_bunchball_admin_form_alter(&$form, &$form_state) {
  $form['bunchball_nitro_logger'] = array(
    '#title' => t('Request type'),
    '#type' => 'select',
    '#options' => array(
      'NitroQueueLogger' => t('Asynchronous'),
      'NitroSynchLogger' => t('Synchronous'),
    ),
    '#default_value' => variable_get('bunchball_nitro_logger', 'NitroQueueLogger'),
  );
}

/**
 * Class that enqueues action log requests and processes them on the next page load to save time
 */
class NitroQueueLogger implements Nitrologger {
  public function log($url, $options = array()) {
    request_queue_request($url, $options, 'bunchball_request_queue');
    bunchball_debug(__METHOD__ . ' Enqueued request for url: %url; return value cannot be reported, due to the queue mechanism', array('%url' => $url));
  }
}