<?php
/**
 * @file
 *    Bunchball user roles module. Add user to Drupal role based on bunchball
 *    level.
 */

/**
 * Implements hook_init().
 * 
 *  - instantiate plugin so that callbacks are initiated.
 * 
 * @global $user
 */
function bunchball_user_roles_init() {
  global $user;
  if ($user->uid > 0) {
    // authenticated users
    ctools_include('plugins');
    $plugin = ctools_get_plugins('bunchball_user_interaction', 'bunchball_user_interaction', 'BunchballUserRoles');
    $class = ctools_plugin_get_class($plugin, 'handler');
    $instance = new $class; //initiate callback
  }
    
}


/**
 * Implements hook_ctools_plugin_directory()
 */
function bunchball_user_roles_ctools_plugin_directory($module, $plugin) {
  if ($module == 'bunchball_user_interaction' && $plugin == 'bunchball_user_interaction') {
    return 'plugins/bunchball_user_interaction';
  }
}
